# Generated by Django 4.1.7 on 2023-03-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.CharField(max_length=50, unique=True)),
                ('courseName', models.CharField(max_length=50, unique=True)),
                ('courseDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('courseCoverUrl', models.CharField(blank=True, max_length=50, null=True)),
                ('courseTypeId', models.IntegerField(unique=True)),
                ('deptCode', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'course_type',
            },
        ),
    ]
