# Generated by Django 4.1.7 on 2023-03-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseTypeId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='deptCode',
            field=models.CharField(max_length=50),
        ),
    ]
