# Generated by Django 4.1.7 on 2023-03-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_coursetypeid_alter_course_deptcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseCoverUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
