# Generated by Django 4.1.7 on 2023-03-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(max_length=20)),
                ('sex', models.CharField(blank=True, choices=[('男', 'Male'), ('女', 'Femail'), ('', 'Unknown')], max_length=5, null=True)),
                ('privCode', models.CharField(max_length=10)),
                ('deptCode', models.CharField(max_length=10)),
                ('phoneNumber', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
