# Generated by Django 4.1.7 on 2023-04-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_courseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videoUrl',
            field=models.FileField(upload_to='F:\\resource\\videos\\2023/04/06/21/42\\1680788579.3934784_0.8235046246179938'),
        ),
    ]
