# Generated by Django 4.1.7 on 2023-04-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_video_videourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='courseId',
            field=models.CharField(default='cid########', max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoId',
            field=models.CharField(default='vid#########', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoUrl',
            field=models.FileField(max_length=255, upload_to='F:\\resource\\videos\\2023/04/07/10/45\\1680835554.374979_0.3425296189411571'),
        ),
    ]
