# Generated by Django 4.1.7 on 2023-04-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_video_courseid_alter_video_videoid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videoName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoUrl',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
