# Generated by Django 4.1.7 on 2023-05-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_video_resolutionversion_video_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='courseId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
