# Generated by Django 4.1.7 on 2023-03-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilegeCode', models.CharField(max_length=20, unique=True)),
                ('privilegeName', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'privilege',
            },
        ),
    ]
